# Generated by Django 4.2.4 on 2023-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("roll_no", models.TextField(max_length=20, unique=True)),
                ("subject1", models.CharField(max_length=50)),
                ("subject2", models.CharField(max_length=50)),
                ("subject3", models.CharField(max_length=50)),
                ("subject4", models.CharField(max_length=50)),
                ("subject5", models.CharField(max_length=50)),
                ("score_subject1", models.IntegerField()),
                ("score_subject2", models.IntegerField()),
                ("score_subject3", models.IntegerField()),
                ("score_subject4", models.IntegerField()),
                ("score_subject5", models.IntegerField()),
                ("image", models.ImageField(upload_to="student_images/")),
                (
                    "student_class",
                    models.PositiveIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ]
                    ),
                ),
            ],
        ),
    ]
