# Generated by Django 4.2.4 on 2023-12-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marksheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdata",
            name="roll_no",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
